//
//  LoginInteractor.swift
//  VIPER
//
//  Created by Chris on 2018/4/13.
//  Copyright (c) 2018年 Chris. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class LoginInteractor {
}

// MARK: - Extensions -

extension LoginInteractor: LoginInteractorInterface {
    //模拟网络访问接口
    func loginUser(with email: String, password: String?, callback: ((Bool) ->())?) {
        DispatchQueue.global(qos: .default).asyncAfter(deadline: DispatchTime.now() + 2.0) {
            if let _callback = callback {
                DispatchQueue.main.async {
                    _callback(true)
                }
            }
        }
    }
}
